### ISSUE TITLE
Build docs

### ISSUE THREAD

**Issue by pbelmans** [pbelmans/hodge-diamond-cutter#21]
Somehow my Sage installation is no longer capable of building the documentation. With Sage 9.6 installed as a binary, it seems that the system's Python is used, even within a Sage shell (so after running `sage -sh`), so that loading bits and pieces of Sage does not work.

**Comment by pbelmans** [comment]
For what it's worth, I just tried it via a Docker image, the same issue arises. Steps to recreate the problem:

0. get the latest image from https://hub.docker.com/r/sagemath/sagemath/
1. `docker run -it -v ~/Documents/Projects/hodge-diamond-cutter:/home/sage/code sagemath/sagemath:latest /bin/sh` (suitably modify to get the right absolute path)
2. `sage --pip install sphynx`
3.  `cd code` and `sage --python -msphinx -M html . _build`

The output is

```
Running Sphinx v4.2.0

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/sage/sage/local/var/lib/sage/venv-python3.9.9/lib/python3.9/site-packages/sphinx/config.py", line 328, in eval_config_file
    exec(code, namespace)
  File "/home/sage/code/conf.py", line 24, in <module>
    import diamond
  File "/home/sage/code/diamond.py", line 130, in <module>
    from sage.arith.misc import binomial, factorial, gcd
  File "/home/sage/sage/local/var/lib/sage/venv-python3.9.9/lib/python3.9/site-packages/sage/arith/misc.py", line 25, in <module>
    from sage.rings.rational_field import QQ
  File "/home/sage/sage/local/var/lib/sage/venv-python3.9.9/lib/python3.9/site-packages/sage/rings/rational_field.py", line 57, in <module>
    from .rational import Rational
  File "sage/rings/rational.pyx", line 95, in init sage.rings.rational (build/cythonized/sage/rings/rational.cpp:40127)
    import sage.rings.real_mpfr
  File "sage/rings/real_mpfr.pyx", line 158, in init sage.rings.real_mpfr (build/cythonized/sage/rings/real_mpfr.c:47136)
    from .rational_field import QQ
ImportError: cannot import name QQ
```

**Comment by pbelmans** [comment]
This is seemingly now fixed.
